name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: setup android-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
        add-to-path: true
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Freedoom-Android
      run: |
          git submodule update --init
          pushd doom/src/main/jni
          ndk-build
          popd
          cd doom
          ../gradlew assembleRelease
          ls -a

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - name: Compress build folder
      run: |
        tar -zcvf build.tar.gz doom/build
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-${{ steps.slug.outputs.sha8 }}-build
        path: build.tar.gz
    
    - name: Rename build.tar.gz file
      run: |
        mv build.tar.gz build-ubunty.tar.gz
    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build-ubuntu.tar.gz
        tag_name: ${{ steps.tag.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
