name: Update submodules

on:
  workflow_dispatch:

jobs:
  updatesubmodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          submodules: 'true'
      - name: git
        run: |
            # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
            git --version
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git submodule update --init --recursive
